### ISSUE TITLE
Vertical Menu Bar in Compact Mode

### ISSUE THREAD

**Issue by bsandler** [tylerhcarter/Triton#12]
Creating a vertical menu bar, rather than horizontal, would take up less screen width and leave more room for working on documents in compact mode.

**Comment by tylerhcarter** [comment]
The more vertical space the menu takes up, the further down the overview panel has to go on the screen. Therefore, we want the menu bar to take up the least amount of vertical space so the overview has plenty of room.

Horizontal space is a little different. Because the overview is already a certain width, any other item in the sidebar can extend to that width without increasing the space taken up by the sidebar. 

Now, here is where my methodology comes out. Because we want to maximize our use of the horizontal space available due to the overview (the widest item on the menu bar), and minimize our use of vertical space (we want the overview to have plenty of room), making the nav bar as wide as the overview and making the action buttons line up next to each other (like now) will end up giving up the most bang for our buck.
