### ISSUE TITLE
Undo Deleted Items

### ISSUE THREAD

**Issue by bsandler** [tylerhcarter/Triton#15]
It would be nice to be able to un-delete a deleted item. A temporary trash can for each browser session would be nice.

**Comment by tylerhcarter** [comment]
The plan to fix this issue is probably going to be undo/redo buttons. Everytime you making a change (add, edit, delete) posts on a thread, the state of the thread after you make that change will be stored. If you make another change and want to undo the change, you press undo and it will restore the thread to its previous state.

Deleting Threads will be handled through a Recycling Bin. All of the threads you delete will be stored in the Recycling bin. Currently it is undecided how that Recycling bin will be cleared, but it will at least allow you to get back threads you've deleted.
